import { createRequire } from "node:module";
const require = createRequire("/Users/priyanshranpura/construction-portal/frontend/package.json");
const { chromium } = require("@playwright/test");
const b = await chromium.launch({args:["--use-gl=angle","--enable-gpu","--ignore-gpu-blocklist"]});
const p = await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
await p.goto("http://localhost:5173/login",{waitUntil:"networkidle"});
await p.waitForSelector('.auth-world[data-live="1"]',{timeout:15000});
await p.waitForTimeout(2500);
const camAt = () => p.evaluate(()=>{const c=document.querySelector("canvas.auth-world");
  return c && c.__cam ? c.__cam : null;});
const vars = () => p.evaluate(()=>{const s=getComputedStyle(document.documentElement);
  return {sun:s.getPropertyValue("--auth-world-sun").trim(), fill:s.getPropertyValue("--auth-world-fill").trim()};});
console.log("world css vars:", JSON.stringify(await vars()));
await p.locator("#login-email").focus(); await p.waitForTimeout(1100);
await p.screenshot({path:".screenshots/login3d/focus-email.png", clip:{x:60,y:30,width:520,height:560}});
await p.locator("#login-password").focus(); await p.waitForTimeout(1100);
await p.screenshot({path:".screenshots/login3d/focus-password.png", clip:{x:60,y:30,width:520,height:560}});
console.log("focus states captured");
await b.close();
