import { createRequire } from "node:module";
const require = createRequire("/Users/priyanshranpura/construction-portal/frontend/package.json");
const { chromium } = require("@playwright/test");
const b = await chromium.launch({args:["--use-gl=angle","--enable-gpu","--ignore-gpu-blocklist"]});
const p = await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
await p.goto("http://localhost:5173/login",{waitUntil:"networkidle"});
await p.waitForSelector('.auth-world[data-live="1"]',{timeout:15000});
await p.waitForTimeout(3000);
console.log(JSON.stringify(await p.evaluate(()=>document.querySelector("canvas.auth-world")?.__geom || "none")));
await p.screenshot({path:".screenshots/login3d/bevel-full.png"});
await p.screenshot({path:".screenshots/login3d/bevel-crop.png", clip:{x:540,y:170,width:640,height:420}});
await b.close();
