-- ===========================================================================
-- This file is intentionally not the schema.
-- ===========================================================================
--
-- It used to be empty, which was misleading: it looked like the source of
-- truth while containing nothing, so there was no way to rebuild the
-- database from the repository.
--
-- The schema now lives in migrations, applied in numbered order:
--
--     database/migrations/001_upgrade_schema.sql
--     database/migrations/002_baseline_supabase.sql
--     database/migrations/003_supabase_rls.sql
--     database/migrations/004_seed_reference_data.sql
--
-- Start with database/migrations/README.md — it explains which files to run
-- for a local database versus a fresh Supabase project.
--
-- To rebuild an empty database from scratch:
--
--     psql "$DATABASE_URL" -v ON_ERROR_STOP=1 \
--       -f database/migrations/002_baseline_supabase.sql \
--       -f database/migrations/003_supabase_rls.sql \
--       -f database/migrations/004_seed_reference_data.sql
--
-- database/snapshots/schema-production.sql is a point-in-time dump kept for
-- reference. It is stale — it describes 18 tables and the database has 47 —
-- so do not build from it.
-- ===========================================================================
