import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { formatCurrency } from "./currency";

const BRAND = {
  name: "Construction Portal",
  dark: "0F172A",
  blue: "2563EB",
  gold: "F59E0B",
  green: "16A34A",
  red: "DC2626",
  light: "F8FAFC",
  border: "CBD5E1",
};

const rgb = (hex) => {
  const value = hex.replace("#", "");
  return [
    parseInt(value.substring(0, 2), 16),
    parseInt(value.substring(2, 4), 16),
    parseInt(value.substring(4, 6), 16),
  ];
};

const toNumber = (value) => Number(value || 0);

const money = formatCurrency;

const formatDate = (value) => (value ? String(value).slice(0, 10) : "");

const getType = (record) =>
  record.record_type || record.payment_sub_type || record.category || "";

const getDate = (record) =>
  record.record_date || record.payment_date || record.created_at || "";

const getDesc = (record) =>
  record.source_name ||
  record.description ||
  record.details ||
  record.material_name ||
  record.worker_name ||
  record.investor_name ||
  getType(record) ||
  "";

const getMode = (record) =>
  record.payment_mode || record.bank_name || record.bank || record.mode || "";

const RECEIPTS = [
  "INVESTOR",
  "GOVERNMENT_BILL",
  "GST_RETURN",
  "COMPANY_CHARGE_PAYMENT",
  "OFFICE_INCOME",
];

const PAYMENTS = [
  "SUBCONTRACTOR",
  "OFFICE",
  "TDS",
  "COMPANY_CHARGE",
  "MATERIAL",
  "LABOUR",
  "SUPERVISOR",
  "SALARY",
  "PF",
  "TAX",
  "OTHER",
];

const isReceipt = (record) =>
  record.payment_type === "Income" || RECEIPTS.includes(getType(record));

const isPayment = (record) =>
  record.payment_type === "Expense" || PAYMENTS.includes(getType(record));

function buildLedger(records = []) {
  const receipts = records.filter(isReceipt);
  const payments = records.filter(isPayment);
  const max = Math.max(receipts.length, payments.length);

  const rows = [];

  for (let i = 0; i < max; i += 1) {
    const r = receipts[i];
    const p = payments[i];

    rows.push([
      r ? formatDate(getDate(r)) : "",
      r ? getDesc(r) : "",
      r ? getMode(r) : "",
      r ? money(r.amount) : "",
      p ? formatDate(getDate(p)) : "",
      p ? getDesc(p) : "",
      p ? getMode(p) : "",
      p ? money(p.amount) : "",
    ]);
  }

  const receiptTotal = receipts.reduce((sum, item) => sum + toNumber(item.amount), 0);
  const paymentTotal = payments.reduce((sum, item) => sum + toNumber(item.amount), 0);
  const balance = receiptTotal - paymentTotal;

  return {
    rows,
    receiptTotal,
    paymentTotal,
    balance,
    finalPaymentTotal: paymentTotal + balance,
  };
}

export function exportLedgerExcel({
  filename = "construction-ledger",
  title = "Construction Ledger",
  records = [],
}) {
  const ledger = buildLedger(records);

  const data = [
    [title],
    ["Generated by Construction Portal"],
    [`Generated Date: ${new Date().toLocaleDateString("en-AU")}`],
    [],
    ["RECEIPT", "", "", "", "PAYMENT", "", "", ""],
    [
      "Date",
      "Description",
      "Bank / Cash",
      "Amount",
      "Date",
      "Description",
      "Bank / Cash",
      "Amount",
    ],
    ...ledger.rows,
    [],
    ["", "", "Balance", money(ledger.balance), "", "", "", ""],
    [
      "",
      "",
      "Total",
      money(ledger.receiptTotal),
      "",
      "",
      "Total",
      money(ledger.finalPaymentTotal),
    ],
  ];

  const ws = XLSX.utils.aoa_to_sheet(data);

  ws["!cols"] = [
    { wch: 14 },
    { wch: 42 },
    { wch: 16 },
    { wch: 18 },
    { wch: 14 },
    { wch: 42 },
    { wch: 16 },
    { wch: 18 },
  ];

  ws["!merges"] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 7 } },
    { s: { r: 1, c: 0 }, e: { r: 1, c: 7 } },
    { s: { r: 2, c: 0 }, e: { r: 2, c: 7 } },
    { s: { r: 4, c: 0 }, e: { r: 4, c: 3 } },
    { s: { r: 4, c: 4 }, e: { r: 4, c: 7 } },
  ];

  const range = XLSX.utils.decode_range(ws["!ref"]);

  for (let row = range.s.r; row <= range.e.r; row += 1) {
    for (let col = range.s.c; col <= range.e.c; col += 1) {
      const cellRef = XLSX.utils.encode_cell({ r: row, c: col });
      if (!ws[cellRef]) continue;

      ws[cellRef].s = {
        font: { name: "Calibri", sz: 11 },
        alignment: { vertical: "center", wrapText: true },
        border: {
          top: { style: "thin", color: { rgb: BRAND.border } },
          bottom: { style: "thin", color: { rgb: BRAND.border } },
          left: { style: "thin", color: { rgb: BRAND.border } },
          right: { style: "thin", color: { rgb: BRAND.border } },
        },
      };
    }
  }

  ["A1"].forEach((cell) => {
    if (ws[cell]) {
      ws[cell].s = {
        font: { bold: true, sz: 18, color: { rgb: "FFFFFF" } },
        fill: { fgColor: { rgb: BRAND.dark } },
        alignment: { horizontal: "center", vertical: "center" },
      };
    }
  });

  ["A2", "A3"].forEach((cell) => {
    if (ws[cell]) {
      ws[cell].s = {
        font: { bold: true, color: { rgb: BRAND.dark } },
        fill: { fgColor: { rgb: BRAND.light } },
        alignment: { horizontal: "center", vertical: "center" },
      };
    }
  });

  ["A5", "E5"].forEach((cell) => {
    if (ws[cell]) {
      ws[cell].s = {
        font: { bold: true, sz: 13, color: { rgb: "FFFFFF" } },
        fill: { fgColor: { rgb: cell === "A5" ? BRAND.green : BRAND.red } },
        alignment: { horizontal: "center", vertical: "center" },
      };
    }
  });

  ["A6", "B6", "C6", "D6", "E6", "F6", "G6", "H6"].forEach((cell) => {
    if (ws[cell]) {
      ws[cell].s = {
        font: { bold: true, color: { rgb: "FFFFFF" } },
        fill: { fgColor: { rgb: BRAND.blue } },
        alignment: { horizontal: "center", vertical: "center" },
      };
    }
  });

  const lastRows = [range.e.r - 1, range.e.r];

  lastRows.forEach((rowIndex) => {
    for (let col = 0; col <= 7; col += 1) {
      const cellRef = XLSX.utils.encode_cell({ r: rowIndex, c: col });
      if (ws[cellRef]) {
        ws[cellRef].s = {
          font: { bold: true, color: { rgb: BRAND.dark } },
          fill: { fgColor: { rgb: "FEF3C7" } },
          alignment: {
            horizontal: col === 3 || col === 7 ? "right" : "center",
            vertical: "center",
          },
          border: {
            top: { style: "thin", color: { rgb: BRAND.dark } },
            bottom: { style: "thin", color: { rgb: BRAND.dark } },
          },
        };
      }
    }
  });

  ws["!rows"] = [{ hpt: 28 }, { hpt: 22 }, { hpt: 22 }, {}, { hpt: 24 }, { hpt: 24 }];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Ledger");
  XLSX.writeFile(wb, `${filename}.xlsx`);
}

export function exportLedgerPDF({
  filename = "construction-ledger",
  title = "Construction Ledger",
  records = [],
}) {
  const ledger = buildLedger(records);

  const doc = new jsPDF("landscape", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFillColor(...rgb(BRAND.dark));
  doc.rect(0, 0, pageWidth, 34, "F");

  doc.setFillColor(...rgb(BRAND.gold));
  doc.rect(0, 34, pageWidth, 3, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(19);
  doc.text(title, 14, 15);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Receipt and Payment Ledger", 14, 24);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(BRAND.name, pageWidth - 14, 15, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    `Generated: ${new Date().toLocaleDateString("en-AU")}`,
    pageWidth - 14,
    24,
    { align: "right" }
  );

  doc.setFillColor(...rgb(BRAND.light));
  doc.roundedRect(14, 43, 55, 18, 3, 3, "F");
  doc.roundedRect(75, 43, 55, 18, 3, 3, "F");
  doc.roundedRect(136, 43, 55, 18, 3, 3, "F");

  doc.setTextColor(...rgb(BRAND.dark));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("Receipt Total", 20, 50);
  doc.text("Payment Total", 81, 50);
  doc.text("Balance", 142, 50);

  doc.setFontSize(12);
  doc.text(money(ledger.receiptTotal), 20, 57);
  doc.text(money(ledger.paymentTotal), 81, 57);
  doc.text(money(ledger.balance), 142, 57);

  autoTable(doc, {
    startY: 69,
    head: [
      ["RECEIPT", "", "", "", "PAYMENT", "", "", ""],
      [
        "Date",
        "Description",
        "Bank / Cash",
        "Amount",
        "Date",
        "Description",
        "Bank / Cash",
        "Amount",
      ],
    ],
    body: ledger.rows,
    theme: "grid",
    styles: {
      font: "helvetica",
      fontSize: 8,
      cellPadding: 2.5,
      lineColor: rgb(BRAND.border),
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: rgb(BRAND.dark),
      textColor: [255, 255, 255],
      fontStyle: "bold",
      halign: "center",
    },
    alternateRowStyles: {
      fillColor: rgb(BRAND.light),
    },
    columnStyles: {
      3: { halign: "right", fontStyle: "bold" },
      7: { halign: "right", fontStyle: "bold" },
    },
    didParseCell: (data) => {
      if (data.section === "head" && data.row.index === 0) {
        if (data.column.index <= 3) {
          data.cell.styles.fillColor = rgb(BRAND.green);
        } else {
          data.cell.styles.fillColor = rgb(BRAND.red);
        }
      }
    },
    didDrawPage: () => {
      doc.setFillColor(...rgb(BRAND.dark));
      doc.rect(0, pageHeight - 11, pageWidth, 11, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text(`${BRAND.name} • Confidential Ledger Report`, 14, pageHeight - 4);

      doc.text(
        `Page ${doc.internal.getNumberOfPages()}`,
        pageWidth - 14,
        pageHeight - 4,
        { align: "right" }
      );
    },
  });

  const finalY = doc.lastAutoTable.finalY + 8;

  autoTable(doc, {
    startY: finalY,
    body: [
      ["Balance", money(ledger.balance)],
      ["Receipt Total", money(ledger.receiptTotal)],
      ["Payment Total + Balance", money(ledger.finalPaymentTotal)],
    ],
    theme: "grid",
    styles: {
      font: "helvetica",
      fontSize: 10,
      fontStyle: "bold",
      cellPadding: 3,
      lineColor: rgb(BRAND.border),
      lineWidth: 0.2,
    },
    columnStyles: {
      0: { fillColor: rgb(BRAND.light) },
      1: { halign: "right" },
    },
    margin: { left: pageWidth - 98 },
  });

  doc.save(`${filename}.pdf`);
}